name: CI
on:
  push:
    branches: [ "**" ]
    
jobs:
  ci:
    name: ''
    uses: sjexpos/ecomm-cicd-actions/.github/workflows/app-ci.yaml@main
    secrets: inherit
    with:
      sonar_project_key: admin-bff
      sonar_project_name: Admin backend for frontend
      docker_image_name: sjexposecomm/admin-bff

